name: Restartvia SSH
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout
        uses: actions/checkout@v2 

      - name: SSH and run commands
        env:
          PRIVATE_KEY: ${{ secrets.ARTIFACT_SSH_KEY }} 
        run: |
          echo "$PRIVATE_KEY" | tr -d '\r' > private_key.pem # Write the private key to a file
          chmod 600 private_key.pem # Set the appropriate permissions for the key file
          ssh -p ${{ secrets.SSH_PORT }} -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.USER }}@${{ secrets.HOST }} <<EOF
            cd ~/${{secrets.APP_PATH}}
            docker compose down
            docker compose up
          EOF
          rm -f private_key.pem
    permissions:
      contents: read
      actions: write
      id-token: write
